const router = require("express").Router();
const userC = require("../controller/userC");
router.post('/register', userC.register);
router.post('/login', userC.login);
router.put('/forgotPassword', userC.forgotPassword);
router.put('/changePassword', userC.changePassword);
router.put('/sendActivationCode', userC.sendActivationCode);
router.post('/verifyCode', userC.verifyCode);
router.get('/getUsers', userC.getUsers);
module.exports = router;